### ISSUE TITLE
不知道这算不算报错，不过反馈就对啦

### ISSUE THREAD

**Issue by BigAppleClass** [TRCStudioDean/LiteSignIn#10]
[15:14:01 INFO]: [LiteSignIn] Enabling LiteSignIn v1.5.5
[15:14:01 INFO]: [LiteSignIn] 语言信息已加载。
[15:14:02 INFO]: LiteSignIn >>> 成功连接到 SQLite 服务器.
[15:14:02 INFO]: LiteSignIn >>> 找不到 PlaceholderAPI ， 已自动关闭该功能。
[15:14:02 ERROR]: [studio.trc.bukkit.litesignin.nms.JsonItemStack] null
java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.NBTTagCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at studio.trc.bukkit.litesignin.nms.JsonItemStack.reloadNMS(JsonItemStack.java:48) ~[[签到]LiteSignIn-1.5.5.jar:?]
        at studio.trc.bukkit.litesignin.Main.onEnable(Main.java:61) ~[[签到]LiteSignIn-1.5.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-74]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-74]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-74]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-74]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-74]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-74]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-74]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:14:02 INFO]: LiteSignIn >>> 插件加载完成。

**Comment by TRCStudioDean** [comment]
1.18版本还没支持而已

**Comment by LeAnhTuan0810** [comment]
Can you support version 1.18?

**Comment by TRCStudioDean** [comment]
> 

Please wait until the Chinese Spring Festival
