### ISSUE TITLE
the 1.18 opengui bug

### ISSUE THREAD

**Issue by jing-shiun** [TRCStudioDean/LiteSignIn#12]
[13:03:36 WARN]: Exception in thread "LiteSignIn-OpeningGUI" java.lang.IllegalArgumentException: Illegal pattern character 'n'
[13:03:36 WARN]:        at java.base/java.text.SimpleDateFormat.compile(SimpleDateFormat.java:849)
[13:03:36 WARN]:        at java.base/java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:657)
[13:03:36 WARN]:        at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:628)
[13:03:36 WARN]:        at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:603)
[13:03:36 WARN]:        at LiteSignIn-1.5.6.jar//studio.trc.bukkit.litesignin.gui.SignInGUI.getGUI(SignInGUI.java:40)
[13:03:36 WARN]:        at LiteSignIn-1.5.6.jar//studio.trc.bukkit.litesignin.event.Menu.lambda$openGUI$0(Menu.java:39)
[13:03:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TRCStudioDean** [comment]
What is you server version?

**Comment by jing-shiun** [comment]
1.18
