### ISSUE TITLE
Error with command named "/lisignin click [Date or playerName] [playerName]" 

### ISSUE THREAD

**Issue by TeQTabanca** [TRCStudioDean/LiteSignIn#13]
### Litesignin Version: 1.6.0

**It can receive today's gift, but if I enter tomorrow's or yesterday's date, it gives an error. Finally, the command named "/lisignin click" accepts the names of players who do not have a name on the server. That is, it accepts all names, letters, numbers, etc. I mean it should only accept those with names on the server.**

### I entered yesterday's date.

```
[11:08:47 INFO]: TeqTabanca issued server command: /litesignin click 2022-4-17 Test
[11:08:47 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'litesignin' in plugin LiteSignIn v1.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'n'
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:845) ~[?:?]
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:653) ~[?:?]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:624) ~[?:?]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:599) ~[?:?]
        at studio.trc.bukkit.litesignin.util.SignInDate.getName(SignInDate.java:303) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.subcommand.ClickCommand.execute(ClickCommand.java:225) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.SignInCommand.callSubCommand(SignInCommand.java:64) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.SignInCommand.onCommand(SignInCommand.java:41) ~[LiteSignIn-1.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
```

### I entered tomorrow's date

```
[11:08:39 INFO]: TeqTabanca issued server command: /litesignin click 2022-4-19 Test
[11:08:40 INFO]: LiteSignIn >>> Plugin cannot obtain the configuration file Messages.yml  path English.Command-Messages.Click.Date-Format, which has been fixed by obtaining the default configuration file.
[11:08:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'litesignin' in plugin LiteSignIn v1.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'n'
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:845) ~[?:?]
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:653) ~[?:?]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:624) ~[?:?]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:599) ~[?:?]
        at studio.trc.bukkit.litesignin.util.SignInDate.getName(SignInDate.java:303) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.subcommand.ClickCommand.execute(ClickCommand.java:220) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.SignInCommand.callSubCommand(SignInCommand.java:64) ~[LiteSignIn-1.6.0.jar:?]
        at studio.trc.bukkit.litesignin.command.SignInCommand.onCommand(SignInCommand.java:41) ~[LiteSignIn-1.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
```

**Comment by TRCStudioDean** [comment]
Give me your configuration file

**Comment by TeQTabanca** [comment]
> Please delete your Messages.yml and use reload, wait for the plugin to regenerate this file.

**I deleted the "messages.yml" file but it gives the same error again. Now I have completely deleted the plugin's files, still giving the same error.**

**Comment by TeQTabanca** [comment]
**it gave this error while logging into the server after deleting the files.**

`[12:32:11 INFO]: LiteSignIn >>> Plugin cannot obtain the configuration file Messages.yml  path English.Join-Event.Messages, which has been fixed by obtaining the default configuration file`

**Comment by TRCStudioDean** [comment]
I have released the fixed version to spigotmc, remember to continue to delete Messages.yml after installation to make it regenerate.

**Comment by TeQTabanca** [comment]
> I have released the fixed version to spigotmc, remember to continue to delete Messages.yml after installation to make it regenerate.

**I downloaded the current version, it didn't give any errors.**
