### ISSUE TITLE
1.19报错

### ISSUE THREAD

**Issue by BigAppleClass** [TRCStudioDean/LiteSignIn#19]
[09:48:52] [Server thread/INFO]: [LiteSignIn] Enabling LiteSignIn v1.6.0
[09:48:52] [Server thread/INFO]: [LiteSignIn] The language information file has been loaded.
[09:48:52] [Server thread/INFO]: [LiteSignIn] Enabled Command Listener .
[09:48:52] [Server thread/INFO]: [LiteSignIn] Enabled Event Listener .
[09:48:52] [Server thread/INFO]: LiteSignIn >>> Successful Connection to SQLite Server.
[09:48:52] [Server thread/INFO]: LiteSignIn >>> The PlaceholderAPI could not be found and the function was automatically turned off.
[09:48:52] [Server thread/ERROR]: null
java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.NBTTagCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at studio.trc.bukkit.litesignin.nms.JsonItemStack.reloadNMS(JsonItemStack.java:50) ~[?:?]
        at studio.trc.bukkit.litesignin.Main.onEnable(Main.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[09:48:52] [Server thread/INFO]: LiteSignIn >>> Plugin are enabled!

**Comment by lRENyaaa** [comment]
这插件作者好像还没更新
你可以先试试我的版本
https://github.com/lRENyaaa/LiteSignIn/releases/

**Comment by TRCStudioDean** [comment]
更了
