### ISSUE TITLE
paper1.21无法加载

### ISSUE THREAD

**Issue by Yukino12333** [TRCStudioDean/LiteSignIn#36]
[22:13:16 INFO]: [LiteSignIn] Enabling LiteSignIn v1.8.1.3
[22:13:16 INFO]: [LiteSignIn] 语言信息已加载。
[22:13:16 INFO]: [LiteSignIn] 已启用 命令监听器 。
[22:13:16 INFO]: [LiteSignIn] 已启用 事件监听器 。
[22:13:16 INFO]: LiteSignIn >>> 成功连接到 SQLite 服务器.
[22:13:16 INFO]: [PlaceholderAPI] Successfully registered internal expansion: litesignin [1.0.0]
[22:13:16 INFO]: LiteSignIn >>> 找到 PlaceholderAPI ， 准备就绪。
[22:13:16 INFO]: LiteSignIn >>> 异步线程开始运行
[22:13:16 ERROR]: Error occurred while enabling LiteSignIn v1.8.1.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at LiteSignIn-1.8.1.3.jar/studio.trc.bukkit.litesignin.nms.NMSManager.getPackageName(NMSManager.java:31) ~[LiteSignIn-1.8.1.3.jar:?]
        at LiteSignIn-1.8.1.3.jar/studio.trc.bukkit.litesignin.nms.NMSManager.reloadNMS(NMSManager.java:56) ~[LiteSignIn-1.8.1.3.jar:?]
        at LiteSignIn-1.8.1.3.jar/studio.trc.bukkit.litesignin.Main.onEnable(Main.java:57) ~[LiteSignIn-1.8.1.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-DEV-4514f41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:13:16 INFO]: [LiteSignIn] Disabling LiteSignIn v1.8.1.3

**Comment by Lumine1909** [comment]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by TRCStudioDean** [comment]
> https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

此Bug已在1.8.1.4版本中修复
