### ISSUE TITLE
/signin itemcollection添加物品后/reload报错

### ISSUE THREAD

**Issue by QianYI-Yan** [TRCStudioDean/LiteSignIn#40]
并不影响使用，但是爆红看着难受

[11:21:16 INFO]: YIN_tx issued server command: /signin reload
[11:21:16 INFO]: LiteSignIn >>> 已断开 MySQL 数据库的连接。
[11:21:17 INFO]: LiteSignIn >>> 成功连接到 MySQL 服务器.
[11:21:17 INFO]: LiteSignIn >>> 找到 PlaceholderAPI ， 准备就绪。
[11:21:17 INFO]: LiteSignIn >>> 异步线程开始运行
[11:21:17 ERROR]: Command exception: /signin reload
org.bukkit.command.CommandException: Unhandled exception executing command 'signin' in plugin LiteSignIn v1.8.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.stop(Thread.java:1654) ~[?:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.async.AutoSave.stopThread(AutoSave.java:51) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.util.PluginControl.reload(PluginControl.java:62) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.subcommand.ReloadCommand.execute(ReloadCommand.java:18) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.SignInCommand.callSubCommand(SignInCommand.java:69) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.SignInCommand.onCommand(SignInCommand.java:46) ~[LiteSignIn-1.8.2.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more
[11:21:19 INFO]: YIN_tx issued server command: /signin reload
[11:21:19 INFO]: LiteSignIn >>> 已断开 MySQL 数据库的连接。
[11:21:20 INFO]: LiteSignIn >>> 成功连接到 MySQL 服务器.
[11:21:20 INFO]: LiteSignIn >>> 找到 PlaceholderAPI ， 准备就绪。
[11:21:20 INFO]: LiteSignIn >>> 异步线程开始运行
[11:21:20 INFO]: LiteSignIn >>> 成功加载 2 个木牌属性，当前服务器内一共有 0 个有效的木牌。
[11:21:20 INFO]: LiteSignIn >>> 玩家数据已保存!
[11:21:21 INFO]: YIN_tx issued server command: /signin reload
[11:21:21 INFO]: LiteSignIn >>> 已断开 MySQL 数据库的连接。
[11:21:22 INFO]: LiteSignIn >>> 成功连接到 MySQL 服务器.
[11:21:22 INFO]: LiteSignIn >>> 找到 PlaceholderAPI ， 准备就绪。
[11:21:22 INFO]: LiteSignIn >>> 异步线程开始运行
[11:21:22 ERROR]: Command exception: /signin reload
org.bukkit.command.CommandException: Unhandled exception executing command 'signin' in plugin LiteSignIn v1.8.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.stop(Thread.java:1654) ~[?:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.async.AutoSave.stopThread(AutoSave.java:51) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.util.PluginControl.reload(PluginControl.java:62) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.subcommand.ReloadCommand.execute(ReloadCommand.java:18) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.SignInCommand.callSubCommand(SignInCommand.java:69) ~[LiteSignIn-1.8.2.0.jar:?]
        at LiteSignIn-1.8.2.0.jar/studio.trc.bukkit.litesignin.command.SignInCommand.onCommand(SignInCommand.java:46) ~[LiteSignIn-1.8.2.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more
[11:21:23 INFO]: YIN_tx issued server command: /signin reload
[11:21:23 INFO]: LiteSignIn >>> 已断开 MySQL 数据库的连接。
[11:21:23 INFO]: LiteSignIn >>> 成功连接到 MySQL 服务器.
[11:21:23 INFO]: LiteSignIn >>> 找到 PlaceholderAPI ， 准备就绪。
[11:21:23 INFO]: LiteSignIn >>> 异步线程开始运行
[11:21:23 INFO]: LiteSignIn >>> 成功加载 2 个木牌属性，当前服务器内一共有 0 个有效的木牌。
[11:21:23 INFO]: LiteSignIn >>> 玩家数据已保存!

**Comment by QianYI-Yan** [comment]
emm
![image](https://github.com/user-attachments/assets/ca1f8c50-eaf0-433d-a024-f6204812f47b)

**Comment by QianYI-Yan** [comment]
两次才会重新加载

**Comment by TRCStudioDean** [comment]
你热重载了是吧

**Comment by QianYI-Yan** [comment]
> 你服务器热重载了是吧

自动保存关了就没事了
![image](https://github.com/user-attachments/assets/7804b7ae-0ab7-47fb-8677-6acb28bc527f)
AI真好用

**Comment by QianYI-Yan** [comment]
> 你服务器热重载了是吧
问一下签到奖励的commands要咋填才能加金币啥的
用{player}还是啥能自动填写玩家名字
